# Site settings
title: Galnet News Fr
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Retrouvez les traductions aproximatives [des actualités galnet](http://www.elitedangerous.com/news/galnet/) en français, selon l'envie
  et la motivation des auteurs.
baseurl: "/galnetfr" # the subpath of your site, e.g. /blog/
url: "http://tbolon.github.io" # the base hostname & protocol for your site
twitter_username: styx31
github_username:  tbolon

# Build settings
markdown: kramdown
highlighter: pygments

# plugins
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

collections:
    people:
        output: true
    geo:
        output: true
